// Libre Audio Suite
// Copyright (C) 2026 Filipe Coelho <falktx@falktx.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

// --------------------------------------------------------------------------------------------------------------------
// require a namespace when including this file

#ifndef FAUSTDR_BEGIN_NAMESPACE
#error missing FAUSTDR_BEGIN_NAMESPACE
#endif
#ifndef FAUSTDR_END_NAMESPACE
#error missing FAUSTDR_END_NAMESPACE
#endif

// --------------------------------------------------------------------------------------------------------------------
// dummy declarations just to get code to compile

namespace {

class Meta {
public:
    void declare(...) {}
};

class UI {
public:
    void addButton(...) {}
    void addCheckButton(...) {}
    void addHorizontalBargraph(...) {}
    void addHorizontalSlider(...) {}
    void addNumEntry(...) {}
    void addVerticalBargraph(...) {}
    void addVerticalSlider(...) {}
    void closeBox(...) {}
    void declare(...) {}
    void openHorizontalBox(...) {}
    void openVerticalBox(...) {}
};

}

// --------------------------------------------------------------------------------------------------------------------
// faust DSP interface as generated by faustdr

#ifdef _WIN32
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

struct FaustDSP
{
    virtual ~FaustDSP() {};
    virtual FaustDSP* clone() = 0;
    virtual float latency() const = 0;
    virtual float get(int index) const = 0;
    virtual int getNumInputs() = 0;
    virtual int getNumOutputs() = 0;
    virtual int getSampleRate() = 0;
    virtual void buildUserInterface(UI* ui_interface) = 0;
    virtual void compute(int count, const float* const* RESTRICT inputs, float** RESTRICT outputs) = 0;
    virtual void init(int sample_rate) = 0;
    virtual void instanceClear() = 0;
    virtual void instanceConstants(int sample_rate) = 0;
    virtual void instanceInit(int sample_rate) = 0;
    virtual void instanceResetUserInterface() = 0;
    virtual void set(int index, float value) = 0;
};

// --------------------------------------------------------------------------------------------------------------------
