// Libre Audio Suite
// Copyright (C) 2026 Filipe Coelho <falktx@falktx.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include "src/DistrhoDefines.h"

// --------------------------------------------------------------------------------------------------------------------
// compiler macros to tweak faust generated code behaviour

// always use floats
#define FAUSTFLOAT float

// define the DSP in the same namespace as DPF
#define FAUSTDR_BEGIN_NAMESPACE START_NAMESPACE_DISTRHO
#define FAUSTDR_END_NAMESPACE END_NAMESPACE_DISTRHO

// --------------------------------------------------------------------------------------------------------------------
// dummy declarations just to get code to compile

namespace {

class Meta {
public:
    void declare(...) {}
};

class UI {
public:
    void addButton(...) {}
    void addCheckButton(...) {}
    void addHorizontalBargraph(...) {}
    void addHorizontalSlider(...) {}
    void addNumEntry(...) {}
    void addVerticalBargraph(...) {}
    void addVerticalSlider(...) {}
    void closeBox(...) {}
    void declare(...) {}
    void openHorizontalBox(...) {}
    void openVerticalBox(...) {}
};

}

// --------------------------------------------------------------------------------------------------------------------
// faust DSP interface as generated by faustdr

struct FaustDSP
{
    FaustDSP* clone();
    float get(int index) const;
    int getNumInputs();
    int getNumOutputs();
    int getSampleRate();
    void buildUserInterface(UI* ui_interface);
    void compute(int count, float** inputs, float** outputs);
    void init(int sample_rate);
    void instanceClear();
    void instanceConstants(int sample_rate);
    void instanceInit(int sample_rate);
    void instanceResetUserInterface();
    void set(int index, float value) const;
};

// --------------------------------------------------------------------------------------------------------------------
