// Libre Audio Suite
// Copyright (C) 2026 Filipe Coelho <falktx@falktx.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

// --------------------------------------------------------------------------------------------------------------------
// require a namespace when including this file

#ifndef FAUSTDR_BEGIN_NAMESPACE
#error missing FAUSTDR_BEGIN_NAMESPACE
#endif
#ifndef FAUSTDR_END_NAMESPACE
#error missing FAUSTDR_END_NAMESPACE
#endif

// --------------------------------------------------------------------------------------------------------------------
// dummy declarations just to get code to compile

namespace {

class Meta {
public:
    void declare(...) {}
};

class UI {
public:
    void addButton(...) {}
    void addCheckButton(...) {}
    void addHorizontalBargraph(...) {}
    void addHorizontalSlider(...) {}
    void addNumEntry(...) {}
    void addVerticalBargraph(...) {}
    void addVerticalSlider(...) {}
    void closeBox(...) {}
    void declare(...) {}
    void openHorizontalBox(...) {}
    void openVerticalBox(...) {}
};

}

// --------------------------------------------------------------------------------------------------------------------
// faust DSP interface as generated by faustdr

struct FaustDSP
{
    FaustDSP* clone();
    float get(int index) const;
    int getNumInputs();
    int getNumOutputs();
    int getSampleRate();
    void buildUserInterface(UI* ui_interface);
    void compute(int count, float** inputs, float** outputs);
    void init(int sample_rate);
    void instanceClear();
    void instanceConstants(int sample_rate);
    void instanceInit(int sample_rate);
    void instanceResetUserInterface();
    void set(int index, float value) const;
};

// --------------------------------------------------------------------------------------------------------------------
// parameter metadata for C++ to be generated by faustdr

struct FaustParameter
{
    const char* label;
    const char* symbol;
    const char* tooltip;
    const char* unit;
    float init;
    float min;
    float max;
    float step;
    bool isBoolean : 1;
    bool isInteger : 1;
    bool isLogarithmic : 1;
    bool isOutput : 1;
    bool isTrigger : 1;
};

template<int count>
using FaustParameters = FaustParameter[count];

// --------------------------------------------------------------------------------------------------------------------
